### ISSUE TITLE
linear gradient colored line chart

### ISSUE THREAD

**Issue by palmchou** [palmchou/ChinaAQITrend#1]
Color the line in AQI line chart with the feature of gradient coloring. 
References can be found at [Threshold Encoding](https://bl.ocks.org/mbostock/3970883) and [Applying a colour gradient to a graph line in d3.js](http://www.d3noob.org/2013/01/applying-colour-gradient-to-graph-line.html).

**Comment by YukiriiiinK** [comment]
implemented in 3dd2e3ccd8050c3d249a9d685f59e53ad3942fe7.
